[package]
name = "gravity_defied_rs"
version = "0.1.0"
authors = ["loomaclin <loo.maclin@protonmail.com>"]

[dependencies]
ggez = "=0.4.4"
byteorder = "=1.2.1"
nphysics2d = "=0.7.2"
nalgebra   = "=0.13.0"
ncollide_geometry = "=0.5.1"
ncollide = "=0.14.1"